dbt_elementary_lab:
  outputs:
    local:
      dbname: elementary
      host: localhost
      pass: elementary
      port: 5432
      schema: elementary
      threads: 1
      type: postgres
      user: elementary
  target: local

elementary:
  outputs:
    default:
      dbname: elementary
      host: localhost
      pass: elementary
      port: 5432
      schema: elementary
      threads: 1
      type: postgres
      user: elementary
