services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: elementary
      POSTGRES_PASSWORD: elementary
      POSTGRES_DB: elementary
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "elementary"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  postgres-volume:
