#!/usr/bin/env bash

# This script is used to source the environment variables from the .env file
# and export them to the current shell environment.

root_dir=$(git rev-parse --show-toplevel)

sed "s|#.*||g" $root_dir/.env \
| grep -v "^\s*$" \
| while read -r line; do
  export $(eval "echo $line")
done
